// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUtqrFruNn3lAJqTufqRxLrvQP29unXW4',
    appId: '1:656962538249:web:410a928d32d57691d3a1d8',
    messagingSenderId: '656962538249',
    projectId: 'genkit-recipe-app-1c0c4',
    authDomain: 'genkit-recipe-app-1c0c4.firebaseapp.com',
    storageBucket: 'genkit-recipe-app-1c0c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAf-4x9T1WyuSSMbiGhuP_JGKXMquqHc',
    appId: '1:656962538249:android:f7fd5b16fd67b46bd3a1d8',
    messagingSenderId: '656962538249',
    projectId: 'genkit-recipe-app-1c0c4',
    storageBucket: 'genkit-recipe-app-1c0c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbyhWsk6aisj4Um-ihMK3RgRbaxwIGBq8',
    appId: '1:656962538249:ios:9f840d43c6c7ccbed3a1d8',
    messagingSenderId: '656962538249',
    projectId: 'genkit-recipe-app-1c0c4',
    storageBucket: 'genkit-recipe-app-1c0c4.firebasestorage.app',
    iosBundleId: 'ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbyhWsk6aisj4Um-ihMK3RgRbaxwIGBq8',
    appId: '1:656962538249:ios:2f097217ea87f71ed3a1d8',
    messagingSenderId: '656962538249',
    projectId: 'genkit-recipe-app-1c0c4',
    storageBucket: 'genkit-recipe-app-1c0c4.firebasestorage.app',
    iosBundleId: 'mac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUtqrFruNn3lAJqTufqRxLrvQP29unXW4',
    appId: '1:656962538249:web:85827dd1ee8639e8d3a1d8',
    messagingSenderId: '656962538249',
    projectId: 'genkit-recipe-app-1c0c4',
    authDomain: 'genkit-recipe-app-1c0c4.firebaseapp.com',
    storageBucket: 'genkit-recipe-app-1c0c4.firebasestorage.app',
  );

}